export const SettingKey = {
    DIAMOND_RATE: 'DIAMOND_RATE',
    MIN_DIAMOND: 'MIN_DIAMOND',
    ACCOUNT_NUMBER: 'ACCOUNT_NUMBER',
    ACCOUNT_NAME: 'ACCOUNT_NAME',
    PREFIX: 'PREFIX',
    PATI_PHONE_NUMBER: 'PATI_PHONE_NUMBER',
    PATI_PASSWORD: 'PATI_PASSWORD',
    SOLVER: 'SOLVER',
}

export const Role = {
    ADMIN: 'ADMIN'
}